services:
  # Nginx Proxy Manager - Web GUI for managing reverse proxy
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'      # HTTP proxy traffic
      - '443:443'    # HTTPS proxy traffic  
      - '8181:81'    # Admin Web UI
    volumes:
      - ./npm-data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network

  # Cloudflare Tunnel - Secure remote access without port forwarding
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    depends_on:
      - nginx-proxy-manager
    networks:
      - proxy-network

  # Speedtest Tracker - Network performance monitoring
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=${SPEEDTEST_APP_KEY}
      - DB_CONNECTION=sqlite
    volumes:
      - ./speedtest-config:/config

networks:
  proxy-network:
    name: proxy-network