---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

# Enable Docker socket monitoring
# Uncomment to enable Docker integration:

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   socket: /var/run/docker.sock